### ISSUE TITLE
The sidebar options are a little too low

### ISSUE THREAD

**Issue by EasyClifton** [rtm516/GeyserAndroid#11]
**Describe the bug**

The sidebar options are a little too low
**To Reproduce**

1. Open the Geyser app
2. Swipe right
3. See error

**Expected behavior**

The Buttons should not be as low

**Screenshots / Videos**

https://media.discordapp.net/attachments/734151097588908084/777493075986874379/Screenshot_20201115-131859_Geyser_Android.png

**Android OS Version**

Android 10

**Android App Version**

1.1.0

**Comment by rtm516** [comment]
After looking into this it's not a bug, it's part of the material design specification. See [here](https://stackoverflow.com/a/30585374) for more info.
