### ISSUE TITLE
App crashes immediately on 1.2.0

### ISSUE THREAD

**Issue by leem919** [rtm516/GeyserAndroid#12]
Title says it all, currently using 1.1.0

**Comment by rtm516** [comment]
Could you try installing https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_GB and pulling the crash log for me?

**Comment by Hellohi3654** [comment]
can confirm this happens

**Comment by RednedEpic** [comment]
> can confirm this happens

Can you install the above so we have more information as to what the issue may be. Saying "it doesn't work" or "I have this issue too doesn't really help us fix the issue. Additionally for the OP, there is an issue template. Please follow that in the future. Thanks!

**Comment by leem919** [comment]
Ah sorry about that, did not realize there was a template. Will get on logs now
