### ISSUE TITLE
Config crash

### ISSUE THREAD

**Issue by bestlinuxgamers** [rtm516/GeyserAndroid#13]
**Describe the bug**
The app crashes if you change the port in the config.

**To Reproduce**
1. Go to Geyser
2. Click on CONFIG
3. Select Port
4. Delete the default 25565 via the delete button (do not select all and delete)

**Expected behavior**
No crash :)

**Screenshots / Videos**
[GB1.zip](https://github.com/rtm516/GeyserAndroid/files/5568774/GB1.zip)

**Android OS Version**
8.0.0 and 7.1.2

**Android App Version**
1.2.2  |   App Revision: 521b8d49b0e43e0e22a30adc9070a0919da58be8

**Geyser Version**
Geyser Version 1.2.0-SNAPSHOT (git-master-4297215) (Java: 1.16.4, Bedrock: 1.16.100.60)

**Comment by rtm516** [comment]
I have a fix for this locally, I will tie it into some other updates and release tomorrow
