### ISSUE TITLE
Stop button desynchronizes when stopping Geyser with a command

### ISSUE THREAD

**Issue by EasyClifton** [rtm516/GeyserAndroid#4]
**Describe the bug**

The "stop" button in the Geyser section gets de-synchronized when shutting Geyser down with `geyser stop` or `geyser shutdown`
**To Reproduce**

1. Go to the Geyser section
2. Start Geyser using the start button
3. Wait for Geyser to start and shut it down using the `geyser stop` or the `geyser shutdown` commands.
4. See Geyser stop but the button remain as "stop" and the config button remain inactive.
**Expected behavior**

The button becomes "start" and the config button becomes active.
**Screenshots / Videos**

**Android OS Version**

Android 10
**Android App Version**

1.0.1-BETA
**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by rtm516** [comment]
Fixed by https://github.com/rtm516/GeyserAndroid/commit/da5e816
